on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      buildConfiguration: 'Release'
      azureWebAppName: 'getservice-webapp'
      artifactName: 'drop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Build the project
        run: dotnet build --configuration ${{ env.buildConfiguration }}

      - name: Publish the project
        run: dotnet publish --configuration ${{ env.buildConfiguration }} --output ${{ github.workspace }}/publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.azureWebAppName }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish

# Optional: Add additional steps for testing, linting, or notifications here
