name: Deploy getService Backend

on:
  push:
    branches:
      - main  # triggers deployment on main branch

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # required for OIDC login
      contents: read

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Cache NuGet packages to speed up builds
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            nuget-

      # 3️⃣ Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 4️⃣ Build .NET API
      - name: Build .NET API
        run: dotnet publish -c Release -o ./bin/publish
        working-directory: ./getService.Api

      # 5️⃣ Debug: List published files
      - name: List published files
        run: ls -R ./getService.Api/bin/publish

      # 6️⃣ Login to Azure via OIDC
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 7️⃣ Deploy .NET backend to App Service
      - name: Deploy .NET backend
        uses: azure/webapps-deploy@v3
        with:
          app-name: getService-api
          package: ./getService.Api/bin/publish
